//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOND_LAST.Entity_Frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENT()
        {
            this.DETAIL_MISSION = new HashSet<DETAIL_MISSION>();
        }
    
        public int ID_AGENT { get; set; }
        public string NOM { get; set; }
        public string Prenom { get; set; }
        public string CIN { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime Date_Ajout { get; set; }
        public string TYPE { get; set; }
        public string PHOTO { get; set; }
        public int ID_SERVICE { get; set; }
        public string ADRESSE { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual SERVICE SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_MISSION> DETAIL_MISSION { get; set; }
    }
}
