//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOND_LAST.Entity_Frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARBURANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARBURANT()
        {
            this.VEHICULEs = new HashSet<VEHICULE>();
            this.BON_PLEIN = new HashSet<BON_PLEIN>();
        }
    
        public int ID_CARBURANT { get; set; }
        public string TYPE_CARBURANT { get; set; }
        public System.DateTime DATE_ADD_CARBURANT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULE> VEHICULEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BON_PLEIN> BON_PLEIN { get; set; }
    }
}
