//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOND_LAST.Entity_Frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_MISSION
    {
        public int ID_MISSION { get; set; }
        public int ID_AGENT { get; set; }
        public int ID_VEHICULE { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual MISSION MISSION { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
        public virtual VEHICULE VEHICULE1 { get; set; }
    }
}
