//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOND_LAST.Entity_Frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MISSION()
        {
            this.DETAIL_MISSION = new HashSet<DETAIL_MISSION>();
        }
    
        public int ID_MISSION { get; set; }
        public string OBJET { get; set; }
        public System.DateTime DATE_DEBUT { get; set; }
        public System.DateTime DATE_FIN { get; set; }
        public string LIEU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_MISSION> DETAIL_MISSION { get; set; }
    }
}
