//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOND_LAST.Entity_Frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPARATION
    {
        public int N_REPARATION { get; set; }
        public System.DateTime DATE_DEBUT_REPARATION { get; set; }
        public System.DateTime DATE_FIN_REPARATION { get; set; }
        public decimal PRIX { get; set; }
        public string PORTER { get; set; }
        public int ID_PANNE { get; set; }
    
        public virtual PANNE PANNE { get; set; }
    }
}
