//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOND_LAST.Entity_Frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULE()
        {
            this.DETAIL_MISSION = new HashSet<DETAIL_MISSION>();
            this.DETAIL_MISSION1 = new HashSet<DETAIL_MISSION>();
            this.PANNEs = new HashSet<PANNE>();
        }
    
        public int ID_VEHICULE { get; set; }
        public string IMATRUCULATION { get; set; }
        public string MATRICULE { get; set; }
        public int ID_MODELE { get; set; }
        public int ID_CATEGORIE { get; set; }
        public int ID_CARBURANT { get; set; }
        public int ID_PROPRIETAIRE { get; set; }
        public System.DateTime DATE_DEBUT { get; set; }
    
        public virtual CARBURANT CARBURANT { get; set; }
        public virtual CATEGORIE CATEGORIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_MISSION> DETAIL_MISSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_MISSION> DETAIL_MISSION1 { get; set; }
        public virtual MODELE MODELE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PANNE> PANNEs { get; set; }
        public virtual PROPRIETAIRE PROPRIETAIRE { get; set; }
    }
}
